# Generated by Django 3.1.3 on 2020-11-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='client_contact',
            field=models.CharField(default='no contact', max_length=200),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_status',
            field=models.CharField(default='new', max_length=200),
        ),
    ]
