# Generated by Django 3.1.3 on 2020-11-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201125_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='client_contact',
        ),
    ]
