# Generated by Django 3.1.3 on 2020-12-01 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201126_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='client_name',
        ),
    ]
