# Generated by Django 3.1.3 on 2020-12-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_task_assignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignment_status',
            field=models.CharField(default='nameandid', max_length=200),
        ),
    ]
